export enum ERoutes {
    HOME = "/",
    LISTEN_AND_REPEAT = "/listen-and-repeat",
    PUT_WORDS = "/put-words",
    BUILD_SENTENCE = "/build-sentence",
    READ = "/read",
    LISTEN_AND_CHOSE = "/listen-and-chose",
    PROFILE = "/profile",
    COURSES = "/courses",
    POPULAR_PHRASES = "/popular-phrases",
    CHAT = "/chat",
    LOGIN = "/login",
    SIGN_UP = "/sign-up",
    QUESTIONNAIRE_START = "/questionnaire-start",
    QUESTIONNAIRE_MOTIVATION = "/questionnaire-motivation",
    QUESTIONNAIRE_VOCABULARY = "/questionnaire-vocabulary",
    QUESTIONNAIRE_PERSONALIZATION = "/questionnaire-personalization",
    QUESTIONNAIRE_CHILDREN = "/questionnaire-children",
    QUESTIONNAIRE_TIME = "/questionnaire-time",
    QUESTIONNAIRE_ANALYZE = "/questionnaire-analyze",
    QUESTIONNAIRE_EMAIL = "/questionnaire-email",
    KNOW = "/know",
    PAY = "/pay",
    LANDING = "/landing",
    PREMIUM = "/premium",
    TERMS_AND_CONDITIONS = "/terms_and_conditions",
    PRIVACY_POLICY = "/privacy_policy",
    SUBSCRIPTIONS = "/terms_of_subcriptions",
    MONEY = "/money_back_guarantee",
    NOTIFICATION = "/notification",
    NEW_LANDING = "/new-landing",
    NEW_PREMIUM = "/new-premium",
    NEW_LANDING_PREMIUM = "/new-landing-premium",
    LANDING_PR = "/landing-pr",
    LANDING_PR2 = "/landing-pr2",
    LANDING_PR3 = "/landing-pr3",
    LANDING_PR4 = "/landing-pr4",
    LANDING_NB = "/landing-nb",
    LANDING_PR_OWN = "/landing-pr-own",
    LANDING_BTRM = "/landing-btrm",
    NEWEST_LANDING = "/newest-landing",
    WORDS = '/words',
    PLAN = '/plan',
    FACT = '/fact',
    NOT_FOUND = "*",

    // Sub-routes
    VOCABULARY = "vocabulary/:courseId",
    GRAMMAR = "grammar/:courseId",
    LISTENING_AND_SPEAKING = "speaking/:courseId",
    CORRECT = "correct",
    PASSWORD = "password",
    EMAIL = "email",
    MANAGE_INFORMATION = "manage-information",
    TERMS = "terms",
    LANGUAGE = "language",
    CONTACT = "contact-us",
    PAYMENTS = "payments",
}

export const getRoutesWithParams = {
    [ERoutes.QUESTIONNAIRE_MOTIVATION]: () => `${ERoutes.QUESTIONNAIRE_MOTIVATION}`
};

export enum LandingType {
    NEW_PREMIUM = "new-premium",
    NEWEST_LANDING = "newest-landing",
    NEW_LANDING = "new-landing"
  }
