export enum EUrls {
    SIGN_IN = "/auth/signin",
    SIGN_UP = "/auth/signup",
    COURSE = '/course',
    COURSE_CREATE = "/course/create",
    COURSE_SHOW = '/course/show',
    COURSE_DELETE = '/course/delete',
    LESSONS = '/lessons',
    LESSONS_CREATE = "/lessons/create",
    LESSONS_SHOW = '/lessons/show',
    LESSONS_DELETE = '/lessons/delete',
    LESSONS_EDIT = '/lessons/edit',
    EXERCISES = '/exercises',
    EXERCISES_CREATE = "/exercises/create",
    EXERCISES_SHOW = '/exercises/show',
    EXERCISES_DELETE = '/exercises/delete',
    RESOURCES = '/resources',
    RESOURCES_CREATE = "/resources/create",
    USERS_PROFILE = '/users/profile',
    USERS_PHOTO = '/users/photo',
    USERS_CHANGE_PASS = '/users/change-pass',
    USERS_CHANGE_PASS_UNAUTH = '/users/password/change',
    USERS_CHANGE_PASS_OLD = '/users/password/change-old',
    USERS_CHANGE_PASS_AUTH = '/users/password/verify-code',
    USERS_PROGRESS = '/users/progress',
    USERS_CLEAR_PROGRESS = '/users/clear_progress',
    USERS_RESET = '/users/password/reset',
    CHAT = '/chat',
    AGENTS = '/chat/agents',
    BOOKS = '/books',
    HOME_COURSE = '/home/course',
    HOME_POPULAR = '/home/phrase',
    CONTACT_US = '/support/contactus',
    CONTAINERS = '/containers',
}

export enum EPayUrls {
    LOCATION = "/location-info",
    CONVERSIONS = "/conversions",
}